#!/usr/bin/env bash
#
# Write a .env with real, generated secrets, for the bundled Postgres and
# object storage.
#
#   ./scripts/setup.sh
#   ./scripts/setup.sh --site https://tasks.example.com --email you@example.com
#
# This exists because `cp .env.example .env` is a trap. It works, which is the
# problem: the stack comes up, everything looks right, and the database
# password is a string that is committed to a public repository. Asking people
# to run `openssl rand` four times and paste the results is the other way to
# get it wrong — so the machine does it.
#
# Deliberately non-interactive. A prompt is fine for a person at a terminal and
# useless in a provisioning script, and this is software people install on
# servers.
#
# Bringing your own Postgres or S3-compatible storage instead of the bundled
# containers is `scripts/setup-interactive.sh` — a person at a terminal has to
# actually type a connection string somewhere, and a prompt is the right place
# for that, not a flag with eight parts.
set -euo pipefail

cd "$(dirname "$0")/.."

SITE_URL="http://localhost"
ACME_EMAIL=""
FORCE=0

while [ $# -gt 0 ]; do
  case "$1" in
    --site) SITE_URL="$2"; shift 2 ;;
    --email) ACME_EMAIL="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    -h|--help)
      sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

# `openssl` is on every machine that can run Docker, but fall back anyway
# rather than emitting a weak secret or an empty one.
secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "${1:-24}"
  else
    LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c $(( ${1:-24} * 2 ))
  fi
}

case "$SITE_URL" in
  http://*|https://*) ;;
  *)
    # The scheme is what tells Caddy whether to get a certificate. Guessing it
    # here would mean guessing whether someone wants HTTPS.
    echo "--site needs a scheme, e.g. https://tasks.example.com" >&2
    exit 2 ;;
esac

if [ -z "$ACME_EMAIL" ]; then
  case "$SITE_URL" in
    https://*)
      echo "--email is required with an https site (Let's Encrypt needs a contact)." >&2
      exit 2 ;;
    # Only used when a certificate is issued, but Caddy won't start on a blank
    # value — so localhost gets a placeholder rather than an empty string.
    *) ACME_EMAIL="admin@localhost" ;;
  esac
fi

if [ -f .env ] && [ "$FORCE" -eq 0 ]; then
  # Never silently. Overwriting this file loses the database password, which
  # means losing the database.
  echo ".env already exists — not touching it." >&2
  echo "To compare it against a newer release:" >&2
  echo "  diff <(grep -o '^[A-Z_]*' .env | sort) <(grep -o '^[A-Z_]*' .env.example | sort)" >&2
  exit 1
fi

umask 077  # the file is about to contain every secret this deployment has

PG_PASSWORD=$(secret 24)
S3_KEY=$(secret 12)
S3_SECRET=$(secret 24)

cat > .env <<EOF
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
#
# This file is the deployment. Back it up somewhere other than the machine it
# is on: without POSTGRES_PASSWORD a database backup is unreadable.
#
# See .env.example for what each of these does. Both databases and object
# storage run in this stack (COMPOSE_PROFILES below) — to point at a managed
# instance instead, run scripts/setup-interactive.sh, or edit this by hand.

SITE_URL=$SITE_URL
ACME_EMAIL=$ACME_EMAIL

COMPOSE_PROFILES=local-db,local-storage

# At least 20 characters, letters/digits/hyphens only — the SuperTokens core
# refuses to start otherwise.
SUPERTOKENS_API_KEY=$(secret 24)

# The bundled Postgres container's own credentials, and what every other
# service uses to reach it — the two are the same database, so they're
# generated together and have to stay in sync if you ever edit this by hand.
POSTGRES_USER=app
POSTGRES_DB=app
POSTGRES_PASSWORD=$PG_PASSWORD
DATABASE_URL=postgresql://app:$PG_PASSWORD@postgres:5432/app
SUPERTOKENS_DATABASE_URL=postgresql://app:$PG_PASSWORD@postgres:5432/supertokens

# The bundled RustFS container's own credentials (RUSTFS_*), and what the API
# and worker use to reach it (S3_*) — again the same box, generated together.
S3_ENDPOINT=http://rustfs:9000
S3_PUBLIC_ENDPOINT=
S3_REGION=us-east-1
S3_BUCKET=media
S3_ACCESS_KEY=$S3_KEY
S3_SECRET_KEY=$S3_SECRET
RUSTFS_ACCESS_KEY=$S3_KEY
RUSTFS_SECRET_KEY=$S3_SECRET

# Email is optional. With SMTP_HOST empty the app logs what it would have sent
# and carries on: invitations still produce a copyable link, and a
# password-reset link appears in \`docker compose logs api\`.
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_START_TLS=true
MAIL_FROM=
EOF

echo "Wrote .env with generated secrets for $SITE_URL"
echo
echo "Next:"
echo "  docker compose up -d"
if [ "$SITE_URL" = "http://localhost" ]; then
  echo "  open http://localhost"
  echo
  echo "To put it on a domain later, edit SITE_URL and ACME_EMAIL in .env."
else
  echo
  echo "Point an A record at this machine first, or Caddy can't get a"
  echo "certificate and the site will be dark while every container looks fine."
fi
echo
echo "Back up .env. It holds the only copy of your database password."
