"""Account suspension: an operator can stop an account signing in.

Two nullable columns, no backfill — every existing account is enabled,
which is what NULL already means.

Hand-written rather than autogenerated. `--autogenerate` wanted to drop
every trigram GIN index, two partial indexes and a unique constraint
alongside the columns, because it can't reflect those types and reads them
as absent from the models. Applying that would have taken search with it.

Revision ID: 0042_account_suspension
Revises: 0041_confirm_notification_email
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0042_account_suspension"
down_revision: str | None = "0041_confirm_notification_email"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("users", sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("disabled_reason", sa.String(length=200), nullable=True))
    # Partial: the question is only ever "who is suspended", and that set is
    # tiny next to the table. Same shape as `ix_tasks_hidden`.
    op.create_index(
        "ix_users_disabled",
        "users",
        ["disabled_at"],
        unique=False,
        postgresql_where=sa.text("disabled_at IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_users_disabled", table_name="users")
    op.drop_column("users", "disabled_reason")
    op.drop_column("users", "disabled_at")
