"""bookmarks: an organisation's shared list of links, ordered, some pinned

Revision ID: 0043_bookmarks
Revises: 0042_account_suspension
Create Date: Phase 9 follow-up

Hand-written rather than autogenerated, the same reason 0042 gives:
`--autogenerate` cannot reflect this schema's trigram GIN indexes, partial
indexes or the CHECK constraints, and wants to drop them alongside whatever
it was actually asked to add.

`created_by_user_id` is SET NULL on purpose — see models/bookmark.py.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0043_bookmarks"
down_revision: str | None = "0042_account_suspension"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    op.create_table(
        "bookmarks",
        sa.Column("id", UUID, primary_key=True, server_default=sa.text("uuidv7()")),
        sa.Column(
            "organisation_id",
            UUID,
            sa.ForeignKey("organisations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_by_user_id",
            UUID,
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False, server_default=""),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint("length(btrim(url)) > 0", name="ck_bookmarks_url"),
    )
    op.create_index("ix_bookmarks_organisation_id", "bookmarks", ["organisation_id"])
    # The one query this table has: one organisation's list, pinned first,
    # then by position.
    op.create_index(
        "ix_bookmarks_org_order", "bookmarks", ["organisation_id", "pinned", "position"]
    )


def downgrade() -> None:
    op.drop_index("ix_bookmarks_org_order", table_name="bookmarks")
    op.drop_index("ix_bookmarks_organisation_id", table_name="bookmarks")
    op.drop_table("bookmarks")
