"""changelog_entries: a per-organisation dated log of what happened

Revision ID: 0046_changelog
Revises: 0045_comment_mention
Create Date: Phase 9 follow-up

Hand-written rather than autogenerated, the same reason 0043 gives:
`--autogenerate` cannot reflect this schema's trigram GIN indexes, partial
indexes or CHECK constraints, and wants to drop them alongside whatever it
was actually asked to add.

`created_by_user_id` is SET NULL on purpose — see models/changelog.py. Two
date columns on purpose as well: `happened_on` is what is being recorded,
`created_at` is when somebody typed it in.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0046_changelog"
down_revision: str | None = "0045_comment_mention"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    op.create_table(
        "changelog_entries",
        sa.Column("id", UUID, primary_key=True, server_default=sa.text("uuidv7()")),
        sa.Column(
            "organisation_id",
            UUID,
            sa.ForeignKey("organisations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "created_by_user_id",
            UUID,
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("happened_on", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.CheckConstraint(
            "length(btrim(description)) > 0", name="ck_changelog_entries_description"
        ),
    )
    op.create_index(
        "ix_changelog_entries_organisation_id", "changelog_entries", ["organisation_id"]
    )
    # The one query this table has: one organisation's log, newest first.
    # Ascending is enough — Postgres scans an index backwards for a DESC
    # order just as happily.
    op.create_index(
        "ix_changelog_entries_org_when", "changelog_entries", ["organisation_id", "happened_on"]
    )


def downgrade() -> None:
    op.drop_index("ix_changelog_entries_org_when", table_name="changelog_entries")
    op.drop_index("ix_changelog_entries_organisation_id", table_name="changelog_entries")
    op.drop_table("changelog_entries")
