"""instance_admins, and organisation-level suspension

Revision ID: 0048_instance_admin
Revises: 0047_changelog_search
Create Date: Phase 9 follow-up

Two additions, both of which sit deliberately *outside* the access model.

`instance_admins` is a table rather than a column on `users`, because `users`
has no `role`/`kind`/`is_admin` column and a test fails the build if one
appears — see models/instance_admin.py for the line between "what may this
person do inside an organisation" (membership and grants, always) and "does
this installation let them see the operator view" (this).

`organisations.suspended_at` is the organisation-level twin of
`users.disabled_at`: enforced once, in `context_for`, upstream of every
visibility expression. Non-destructive — nothing is deleted and clearing it
restores everything.

Hand-written rather than autogenerated, the same reason 0043 and 0046 give.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0048_instance_admin"
down_revision: str | None = "0047_changelog_search"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    op.create_table(
        "instance_admins",
        sa.Column("id", UUID, primary_key=True, server_default=sa.text("uuidv7()")),
        sa.Column(
            "user_id",
            UUID,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "organisations", sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "organisations", sa.Column("suspended_reason", sa.String(length=200), nullable=True)
    )


def downgrade() -> None:
    op.drop_column("organisations", "suspended_reason")
    op.drop_column("organisations", "suspended_at")
    op.drop_table("instance_admins")
