"""messages.via, and the idempotency_keys table

Revision ID: 0049_attribution_and_idempotency
Revises: 0048_instance_admin
Create Date: Phase 9 follow-up

Two additions, both of them about an assistant writing rather than a person.

`messages.via` records what acted on the author's behalf — the name of the
personal access token or OAuth client that posted a comment. Attribution,
not authorship: `user_id` is still whose comment it is, because an assistant
acts *as* the person whose credential it holds (see app/mcp/server.py's one
rule). NULL on every row that existed before this and on everything typed in
the web app, which is why there is no default and no backfill: "a person
typed it" is exactly what NULL already meant.

`idempotency_keys` makes a retried write safe to retry. A timeout on a
create says nothing about whether the row exists, and calling again without
a key is how one request becomes two tasks. See models/idempotency.py for
why this is a table rather than a column on each thing that can be created.

Hand-written rather than autogenerated, the same reason 0043, 0046 and 0048
give: autogenerate cannot see the partial and expression indexes this schema
is full of, and offers to drop every one of them.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0049_attribution_and_idempotency"
down_revision: str | None = "0048_instance_admin"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    op.add_column("messages", sa.Column("via", sa.String(length=80), nullable=True))

    op.create_table(
        "idempotency_keys",
        sa.Column("id", UUID, primary_key=True, server_default=sa.text("uuidv7()")),
        sa.Column(
            "user_id",
            UUID,
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("tool", sa.String(length=80), nullable=False),
        # Nullable on purpose: NULL is "claimed but not finished", which
        # services/idempotency.py tells apart from "in flight" by age alone.
        sa.Column("entity_id", UUID, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        # The whole mechanism: two concurrent retries both insert, exactly
        # one wins, and the loser reads back what the winner did.
        sa.UniqueConstraint("user_id", "key", name="uq_idempotency_keys_user_key"),
    )


def downgrade() -> None:
    op.drop_table("idempotency_keys")
    op.drop_column("messages", "via")
